services:
  app:
    image: 'lherrera0/bank-api:latest'
    container_name: bank-api
    ports:
      - 7500:7500
    environment:
      - db_url=jdbc:postgresql://database-1.c7jfv3zcy9rz.us-west-1.rds.amazonaws.com:5432/postgres
      - db_user=java_login
      - db_password=s3cur3m3
  prom:
    image: 'prom/prometheus'
    container_name: prom-container
      #Specify the prometheus file in our host system and move it into the container!
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graf:
    image: 'grafana/grafana'
    ports:
      - 8000:3000
