pipeline {
    agent any
    stages {
        stage('Docker build'){
            steps{
                sh 'git pull https://github.com/2205JavaSRE/this.Super-Project2.git'
                sh 'docker build -t lherrera0/bank-api ./BankAPI'
            }
        }
        stage('Docker image push'){
            steps{
                sh 'docker login -u lherrera0 -p c359357d-6662-499f-9b5c-3f560ca2153f'
                sh 'docker image push lherrera0/bank-api:latest'
            }
        }
        stage('Kubernetes apply changes') { 
            steps {
				sh 'aws --profile ben-sre-1368 configure set aws_access_key_id &quot;AKIA4OK5FKIYREAUQUPV&quot;'
				sh 'echo &quot;AWS access key id set&quot;'
				sh 'aws --profile ben-sre-1368 configure set aws_secret_access_key &quot;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&quot;'
				sh 'echo &quot;AWS secret access key set&quot;'
				sh 'aws eks --region us-east-1 update-kubeconfig --name ben-sre-1368 --profile ben-sre-1368'
				sh 'kubectl config get-contexts'
				sh 'kubectl rollout restart deployment bankapi-deployment -n this-dot-super-space'
            }
        }
    }
}
